<a href="https://colab.research.google.com/github/webanetStorm/AI_webanet/blob/master/AI_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Пример 1.2.1.** Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


**Пример 1.2.2.** Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.}$

In [4]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)

print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


**Пример 1.2.3.** Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [2]:
import numpy as np

Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(),Z.mean()
print(Zmin, Zmax, Zmean)

0.007137509707888623 0.9920860613436094 0.5140682241821438


**Пример 1.2.4.** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [5]:
import numpy as np

A = np.arange(25).reshape(5,5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Пример 1.2.5.** Выяснить результат следующих выражений:
0 * np.nan ,
np.nan == np.nan ,
np.inf > np.nan ,
np.nan - np.nan ,
0.3 == 3 * 0.1}$

In [6]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


**Пример 1.2.6.** Отсортировать массив.

In [12]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


**Задание 1.3.1.** Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [8]:
from numpy import *

matrix = zeros((8, 8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**Задание 1.3.2.** Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [9]:
from numpy import *

matrix = zeros((5, 5))
matrix += arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**Зажание 1.3.3.** Создать массив 3x3x3 со случайными значениями.

In [11]:
from numpy import *

print(random.rand(3, 3, 3))

[[[0.7633443  0.3526827  0.86116344]
  [0.89490799 0.09133445 0.04697962]
  [0.76624863 0.91895869 0.66658284]]

 [[0.76855444 0.35675107 0.78557967]
  [0.79409658 0.81556158 0.06325784]
  [0.18711352 0.67952544 0.76420769]]

 [[0.55043639 0.30442732 0.76685249]
  [0.53727376 0.64409618 0.73514161]
  [0.21344904 0.63939488 0.7990822 ]]]


**Задание 1.3.4.** Создать матрицу с 0 внутри, и 1 на границах.

In [14]:
from numpy import *

matrix = zeros((5, 5))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Задание 1.3.5.** Создайте массив и отсортируйте его по убыванию.

In [17]:
print(sorted([27, 55, -43, 100, 900, 0, 1, 7, -5])[::-1])

[900, 100, 55, 27, 7, 1, 0, -5, -43]


**Задание 1.3.6.** Создайте матрицу, выведите ее форму, размер и размерность.

In [22]:
from numpy import *

matrix = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Форма:', matrix.shape, '\nРазмер:', matrix.size, '\nРазмерность:', matrix.ndim)

Форма: (3, 3) 
Размер: 9 
Размерность: 2


**Задание 2.2.1.** Создать Series из списка Python, словаря Python, и массива Numpy(установить буквенные метки для последнего.

In [24]:
import pandas as pd
import numpy as np

lst=[1, 2, 3, 4, 5]
d={'a': 1,'b': 2,'c': 3}
ndarr=np.array([1, 2, 3, 4, 5])

s1=pd.Series(lst)
s2=pd.Series(d)
s3=pd.Series(ndarr,['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


**Задание 2.2.2.** Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)

In [30]:
from pandas import *

s1 = Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = Series([5, 4, 3, 2, 1])

print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


$\small\textbf{2.2.3 Пример}$ $\small\textit{Создайте новый фрейм данных.}$

In [31]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

**Пример 2.2.4.** Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

**Пример 2.2.5.** Проанализировать характеристики фрейма данных.

In [ ]:
import pandas as pd

url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

**Пример 2.2.6.** Выберите индивидуальные данные или срезы фрейма данных.

In [ ]:
import pandas as pd

url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.iloc[1:4]

**Пример 2.2.7.** Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [ ]:
import pandas as pd

url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe[dataframe['PClass'] == '1st'].head(2)

**Задание 2.3.1.** Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [37]:
from pandas import *

print(sum((Series([2, 6, 3, 8]) - Series([1, 9, 4, 7])) ** 2) ** 0.5)

3.4641016151377544


**Задание 2.3.2.** Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [46]:
from pandas import *

print(read_csv('https://raw.githubusercontent.com/akmand/datasets/main/wine.csv').head())

       1     2     3     4    5     6     7     8     9    10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  y  
0  1065  1  
1  1050  1  
2  1185  1  
3  1480  1  
4   735  1  


**Задание 2.3.3.** Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [47]:
from pandas import *

dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/wine.csv')

print(dataframe.columns)
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())
print("\n")

print(dataframe['1'])
print("\n")
print(dataframe.iloc[2:5, 3:6])
print("\n")

filtered_df = dataframe[dataframe['1'] > 13.0]
print(filtered_df.head())

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       'y'],
      dtype='object')
       1     2     3     4    5     6     7     8     9    10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   

     13  y  
0  1065  1  
1  1050  1  


         1     2     3     4    5     6     7     8     9    10    11    12  \
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.2  0.61  1.60   

      13  y  
175  835  3  
176  840  3  
177  560  3  


(178, 14)


                1           2           3           4           5           6  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    13.000618    2.336348    2.366517   19.494944   99.741573  

**Пример 3.2.1.** Прошкалируйте числовой признак в диапазон между двумя значениями.

In [48]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

**Пример 3.2.2.** Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [49]:
import numpy as np
from sklearn import preprocessing

x=np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized=scaler.fit_transform(x)

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())
standardized

Среднее: 0
Стандартное отклонение: 1.0


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

**Пример 3.2.3.** Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
    'B':[103.02,107.26,110.35,114.23,114.68],
    'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [51]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({
  'A': [14.00, 90.20, 90.95, 96.27, 91.21],
  'B': [103.02,107.26,110.35,114.23,114.68],
  'C': ['big', 'small', 'big', 'small', 'small']
})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

**Задание 3.3.2.** Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [52]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

X = df.drop('species', axis=1)
y = df['species']

scaler_minmax = MinMaxScaler()
X['sepal_length_cm'] = scaler_minmax.fit_transform(X[['sepal_length_cm']])

scaler_z = StandardScaler()
X['sepal_width_cm'] = scaler_z.fit_transform(X[['sepal_width_cm']])

print(X.head(2))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0         0.222222        1.032057              1.4             0.2
1         0.166667       -0.124958              1.4             0.2
